# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL: "https://remvn.dev/"
title: "My Rabbit Hole in Programming"
defaultContentLanguage: en
enableRobotsTXT: true
paginate: 10
summaryLength: 0

services:
  googleAnalytics:
    ID: G-D3VB7YFCTH

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  series: series
  tag: tags
